name: Ruby

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      matrix:
        ruby: [3.0.5, 3.1.3]
        gemfile: [Gemfile, gemfiles/rails60.gemfile]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Code Climate
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Build and Test
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        RUBY_VERSION: ${{ matrix.ruby }}
      run: |
        if [ $RUBY_VERSION == "2.5.x" ] ;
          then gem install bundler
        fi
        bundle install --jobs 4 --retry 3
        bundle exec rake
        if [ `basename $BUNDLE_GEMFILE` == "Gemfile" ] && [ $RUBY_VERSION == "2.7.x" ] && [ ! -z ${CC_TEST_REPORTER_ID} ] ;
          then ./cc-test-reporter after-build --exit-code $? ;
        fi
